Create and edit working date slots
mtolbol/sharetribe pull request #24
Opened 2019-05-22 11:00 UTC by olepalm

## WorkingDateSlots#index
![Screenshot 2019-05-22 at 12 58 58](https://user-images.githubusercontent.com/5213037/58169597-6f3ece80-7c91-11e9-9911-c4324015116e.png)

## WorkingDateSlots#edit
![Screenshot 2019-05-22 at 12 59 11](https://user-images.githubusercontent.com/5213037/58169603-74038280-7c91-11e9-80eb-0311b386c470.png)

2019-05-22 14:00 UTC, koppen requested changes
Hvad kan vi gøre ved UI'et? Det står jævnt rodet lige pt. Mangler der eventuelt bare nogle `<div class="row">...</div>`?

2019-05-22 14:00 UTC, koppen commented on app/controllers/working_date_slots_controller.rb
> +        :till
:abc: 🙏

2019-05-23 08:01 UTC, olepalm commented
Formen har lige fået nogle quickfix rows, der gør det lidt pænere

2019-05-23 08:05 UTC, koppen approved these changes

2019-05-23 08:10 UTC, merged