Add working date slot
mtolbol/sharetribe pull request #6
Opened 2019-05-08 11:27 UTC by olepalm

Adds WorkingDateSlot, which is basically identical to WorkingTimeSlot, except we can assign dates to the WorkingDateSlot.

This PR includes some much needed behaviour specs to WorkingTImeSlot.

2019-05-08 13:16 UTC, koppen requested changes

2019-05-08 13:16 UTC, koppen commented on app/models/listing/working_date_slot.rb
> +    till_time = Time.zone.parse("#{now.year}/#{now.month}/#{now.day} #{till}")
Hvorfor har `now` noget at sige her - burde det ikke tage udgangspunkt i `date`?

2019-05-08 13:16 UTC, koppen commented on app/models/listing/working_date_slot.rb
> +class Listing::WorkingDateSlot < ApplicationRecord
Kan vi tilføje en smule dokumentation her, forklaring af, hvad `WorkingDateSlot` er - især ift `WorkingTimeSlot`.

2019-05-08 13:16 UTC, koppen commented on db/structure.sql
> +  `profile_meta_description` text,
Hvorfor ændrer defaults sig her, når du ikke har pillet ved dem?

2019-05-08 14:10 UTC, olepalm commented on db/structure.sql
> +  `profile_meta_description` text,
Dunno, lokale forskelle i MySql version? Jeg har reverted ændringerne, men de dukker nok op igen efter næste migration.

2019-05-08 20:07 UTC, koppen commented on db/structure.sql
> +  `profile_meta_description` text,
`git add -p` ;)

2019-05-08 20:10 UTC, koppen requested changes

2019-05-08 20:10 UTC, koppen commented on app/models/listing/working_date_slot.rb
> +    now = Time.zone.now
`now` bliver ikke længere brugt, så lad os droppe den.

2019-05-08 20:10 UTC, koppen commented on app/models/listing/working_time_slot.rb
> +# for the main purpose of repeating the hours across many weekdays in the future
👍

2019-05-09 06:28 UTC, olepalm commented on db/structure.sql
> +  `profile_meta_description` text,
Jep, men at tilføje ændringer til `structure.db` progressively, kan ret tit være en omstændig affære...

2019-05-09 06:56 UTC, koppen approved these changes

2019-05-09 06:56 UTC, merged